// Instituições Financeiras do Brasil com ícones
export interface InstituicaoFinanceira {
  nome: string;
  codigo: string;
  icone: string; // Nome do ícone do lucide-react
  tipo: 'banco' | 'cooperativa' | 'fintech' | 'corretora';
}

export const INSTITUICOES_FINANCEIRAS: InstituicaoFinanceira[] = [
  // Bancos Públicos
  { nome: 'Banco do Brasil', codigo: '001', icone: 'Building2', tipo: 'banco' },
  { nome: 'Caixa Econômica Federal', codigo: '104', icone: 'Building2', tipo: 'banco' },
  { nome: 'Banco Nacional de Desenvolvimento Econômico e Social', codigo: '007', icone: 'Building2', tipo: 'banco' },
  
  // Bancos Privados Grandes
  { nome: 'Itaú Unibanco', codigo: '341', icone: 'Building2', tipo: 'banco' },
  { nome: 'Bradesco', codigo: '237', icone: 'Building2', tipo: 'banco' },
  { nome: 'Santander', codigo: '033', icone: 'Building2', tipo: 'banco' },
  { nome: 'Banco Inter', codigo: '077', icone: 'Building2', tipo: 'banco' },
  { nome: 'Nubank', codigo: '260', icone: 'CreditCard', tipo: 'fintech' },
  { nome: 'Banco Original', codigo: '212', icone: 'Building2', tipo: 'banco' },
  { nome: 'Banco Pan', codigo: '623', icone: 'Building2', tipo: 'banco' },
  { nome: 'Banco C6', codigo: '336', icone: 'Building2', tipo: 'banco' },
  { nome: 'Banco Neon', codigo: '735', icone: 'Building2', tipo: 'fintech' },
  { nome: 'Banco Next', codigo: '237', icone: 'Building2', tipo: 'banco' },
  { nome: 'Banco Digio', codigo: '335', icone: 'Building2', tipo: 'fintech' },
  { nome: 'Banco Will', codigo: '280', icone: 'Building2', tipo: 'fintech' },
  { nome: 'Banco BS2', codigo: '218', icone: 'Building2', tipo: 'banco' },
  { nome: 'Banco Sofisa', codigo: '637', icone: 'Building2', tipo: 'banco' },
  { nome: 'Banco Rendimento', codigo: '633', icone: 'Building2', tipo: 'banco' },
  { nome: 'Banco Daycoval', codigo: '707', icone: 'Building2', tipo: 'banco' },
  { nome: 'Banco Votorantim', codigo: '655', icone: 'Building2', tipo: 'banco' },
  { nome: 'Banco Safra', codigo: '422', icone: 'Building2', tipo: 'banco' },
  { nome: 'Banco BTG Pactual', codigo: '208', icone: 'Building2', tipo: 'banco' },
  { nome: 'Banco XP', codigo: '102', icone: 'TrendingUp', tipo: 'corretora' },
  { nome: 'Banco Modal', codigo: '746', icone: 'Building2', tipo: 'banco' },
  { nome: 'Banco Genial', codigo: '278', icone: 'Building2', tipo: 'banco' },
  { nome: 'Banco Agibank', codigo: '121', icone: 'Building2', tipo: 'banco' },
  { nome: 'Banco Alfa', codigo: '025', icone: 'Building2', tipo: 'banco' },
  { nome: 'Banco ABC Brasil', codigo: '246', icone: 'Building2', tipo: 'banco' },
  { nome: 'Banco ABN Amro', codigo: '075', icone: 'Building2', tipo: 'banco' },
  { nome: 'Banco Alvorada', codigo: '641', icone: 'Building2', tipo: 'banco' },
  { nome: 'Banco Arbi', codigo: '213', icone: 'Building2', tipo: 'banco' },
  { nome: 'Banco Atlas', codigo: '143', icone: 'Building2', tipo: 'banco' },
  { nome: 'Banco Azteca', codigo: '019', icone: 'Building2', tipo: 'banco' },
  { nome: 'Banco Banestes', codigo: '021', icone: 'Building2', tipo: 'banco' },
  { nome: 'Banco Banrisul', codigo: '041', icone: 'Building2', tipo: 'banco' },
  { nome: 'Banco BBM', codigo: '107', icone: 'Building2', tipo: 'banco' },
  { nome: 'Banco BNP Paribas', codigo: '752', icone: 'Building2', tipo: 'banco' },
  { nome: 'Banco Bradescard', codigo: '063', icone: 'Building2', tipo: 'banco' },
  { nome: 'Banco BRB', codigo: '070', icone: 'Building2', tipo: 'banco' },
  { nome: 'Banco BVA', codigo: '655', icone: 'Building2', tipo: 'banco' },
  { nome: 'Banco Cacique', codigo: '473', icone: 'Building2', tipo: 'banco' },
  { nome: 'Banco Cargill', codigo: '040', icone: 'Building2', tipo: 'banco' },
  { nome: 'Banco Cetelem', codigo: '739', icone: 'Building2', tipo: 'banco' },
  { nome: 'Banco Citibank', codigo: '745', icone: 'Building2', tipo: 'banco' },
  { nome: 'Banco Clássico', codigo: '241', icone: 'Building2', tipo: 'banco' },
  { nome: 'Banco CNH Capital', codigo: '350', icone: 'Building2', tipo: 'banco' },
  { nome: 'Banco Cooperativa do Brasil', codigo: '756', icone: 'Building2', tipo: 'cooperativa' },
  { nome: 'Banco Cooperativo Sicredi', codigo: '748', icone: 'Building2', tipo: 'cooperativa' },
  { nome: 'Banco Credicard', codigo: '222', icone: 'Building2', tipo: 'banco' },
  { nome: 'Banco Credit Suisse', codigo: '505', icone: 'Building2', tipo: 'banco' },
  { nome: 'Banco Cruzeiro do Sul', codigo: '126', icone: 'Building2', tipo: 'banco' },
  { nome: 'Banco da Amazônia', codigo: '003', icone: 'Building2', tipo: 'banco' },
  { nome: 'Banco da China', codigo: '083', icone: 'Building2', tipo: 'banco' },
  { nome: 'Banco de Brasília', codigo: '070', icone: 'Building2', tipo: 'banco' },
  { nome: 'Banco de La Nación Argentina', codigo: '300', icone: 'Building2', tipo: 'banco' },
  { nome: 'Banco de La Provincia de Buenos Aires', codigo: '495', icone: 'Building2', tipo: 'banco' },
  { nome: 'Banco de Tokyo-Mitsubishi', codigo: '064', icone: 'Building2', tipo: 'banco' },
  { nome: 'Banco Dibens', codigo: '335', icone: 'Building2', tipo: 'banco' },
  { nome: 'Banco do Estado de Sergipe', codigo: '047', icone: 'Building2', tipo: 'banco' },
  { nome: 'Banco do Estado do Espírito Santo', codigo: '021', icone: 'Building2', tipo: 'banco' },
  { nome: 'Banco do Estado do Pará', codigo: '037', icone: 'Building2', tipo: 'banco' },
  { nome: 'Banco do Estado do Rio Grande do Sul', codigo: '041', icone: 'Building2', tipo: 'banco' },
  { nome: 'Banco do Nordeste', codigo: '004', icone: 'Building2', tipo: 'banco' },
  { nome: 'Banco Fator', codigo: '265', icone: 'Building2', tipo: 'banco' },
  { nome: 'Banco Fibra', codigo: '224', icone: 'Building2', tipo: 'banco' },
  { nome: 'Banco Fidis', codigo: '626', icone: 'Building2', tipo: 'banco' },
  { nome: 'Banco Fivesc', codigo: '393', icone: 'Building2', tipo: 'banco' },
  { nome: 'Banco Flem', codigo: '094', icone: 'Building2', tipo: 'banco' },
  { nome: 'Banco Ford', codigo: '387', icone: 'Building2', tipo: 'banco' },
  { nome: 'Banco GMAC', codigo: '390', icone: 'Building2', tipo: 'banco' },
  { nome: 'Banco Guanabara', codigo: '612', icone: 'Building2', tipo: 'banco' },
  { nome: 'Banco Honda', codigo: '062', icone: 'Building2', tipo: 'banco' },
  { nome: 'Banco HSBC', codigo: '399', icone: 'Building2', tipo: 'banco' },
  { nome: 'Banco IBM', codigo: '301', icone: 'Building2', tipo: 'banco' },
  { nome: 'Banco Industrial do Brasil', codigo: '604', icone: 'Building2', tipo: 'banco' },
  { nome: 'Banco Industrial e Comercial', codigo: '320', icone: 'Building2', tipo: 'banco' },
  { nome: 'Banco Indusval', codigo: '653', icone: 'Building2', tipo: 'banco' },
  { nome: 'Banco Inbursa', codigo: '012', icone: 'Building2', tipo: 'banco' },
  { nome: 'Banco Itaú', codigo: '341', icone: 'Building2', tipo: 'banco' },
  { nome: 'Banco Itaucard', codigo: '376', icone: 'Building2', tipo: 'banco' },
  { nome: 'Banco Itauleasing', codigo: '379', icone: 'Building2', tipo: 'banco' },
  { nome: 'Banco J. Safra', codigo: '422', icone: 'Building2', tipo: 'banco' },
  { nome: 'Banco J.P. Morgan', codigo: '376', icone: 'Building2', tipo: 'banco' },
  { nome: 'Banco John Deere', codigo: '217', icone: 'Building2', tipo: 'banco' },
  { nome: 'Banco KDB', codigo: '076', icone: 'Building2', tipo: 'banco' },
  { nome: 'Banco Luso Brasileiro', codigo: '600', icone: 'Building2', tipo: 'banco' },
  { nome: 'Banco Máxima', codigo: '243', icone: 'Building2', tipo: 'banco' },
  { nome: 'Banco Mercantil do Brasil', codigo: '389', icone: 'Building2', tipo: 'banco' },
  { nome: 'Banco Mercantil de Investimentos', codigo: '370', icone: 'Building2', tipo: 'banco' },
  { nome: 'Banco Meridian', codigo: '477', icone: 'Building2', tipo: 'banco' },
  { nome: 'Banco Mitsubishi', codigo: '456', icone: 'Building2', tipo: 'banco' },
  { nome: 'Banco Mizuho', codigo: '370', icone: 'Building2', tipo: 'banco' },
  { nome: 'Banco Modal', codigo: '746', icone: 'Building2', tipo: 'banco' },
  { nome: 'Banco Morada', codigo: '637', icone: 'Building2', tipo: 'banco' },
  { nome: 'Banco Morgan Stanley', codigo: '066', icone: 'Building2', tipo: 'banco' },
  { nome: 'Banco Multiplic', codigo: '341', icone: 'Building2', tipo: 'banco' },
  { nome: 'Banco Nossa Caixa', codigo: '151', icone: 'Building2', tipo: 'banco' },
  { nome: 'Banco OBOE Crédito', codigo: '169', icone: 'Building2', tipo: 'banco' },
  { nome: 'Banco Original', codigo: '212', icone: 'Building2', tipo: 'banco' },
  { nome: 'Banco Ourinvest', codigo: '712', icone: 'Building2', tipo: 'banco' },
  { nome: 'Banco Palmas', codigo: '630', icone: 'Building2', tipo: 'banco' },
  { nome: 'Banco Panamericano', codigo: '623', icone: 'Building2', tipo: 'banco' },
  { nome: 'Banco Patagonia', codigo: '062', icone: 'Building2', tipo: 'banco' },
  { nome: 'Banco Paulista', codigo: '611', icone: 'Building2', tipo: 'banco' },
  { nome: 'Banco Pecúnia', codigo: '254', icone: 'Building2', tipo: 'banco' },
  { nome: 'Banco Pine', codigo: '643', icone: 'Building2', tipo: 'banco' },
  { nome: 'Banco Pottencial', codigo: '638', icone: 'Building2', tipo: 'banco' },
  { nome: 'Banco PSA Finance', codigo: '290', icone: 'Building2', tipo: 'banco' },
  { nome: 'Banco Rabobank', codigo: '010', icone: 'Building2', tipo: 'banco' },
  { nome: 'Banco RCI', codigo: '356', icone: 'Building2', tipo: 'banco' },
  { nome: 'Banco Real', codigo: '356', icone: 'Building2', tipo: 'banco' },
  { nome: 'Banco Rendimento', codigo: '633', icone: 'Building2', tipo: 'banco' },
  { nome: 'Banco Ribeirão Preto', codigo: '741', icone: 'Building2', tipo: 'banco' },
  { nome: 'Banco Rodobens', codigo: '120', icone: 'Building2', tipo: 'banco' },
  { nome: 'Banco Rural', codigo: '453', icone: 'Building2', tipo: 'banco' },
  { nome: 'Banco Safra', codigo: '422', icone: 'Building2', tipo: 'banco' },
  { nome: 'Banco Santander', codigo: '033', icone: 'Building2', tipo: 'banco' },
  { nome: 'Banco Santander Brasil', codigo: '033', icone: 'Building2', tipo: 'banco' },
  { nome: 'Banco Schahin', codigo: '250', icone: 'Building2', tipo: 'banco' },
  { nome: 'Banco Semear', codigo: '743', icone: 'Building2', tipo: 'banco' },
  { nome: 'Banco Serasa', codigo: '743', icone: 'Building2', tipo: 'banco' },
  { nome: 'Banco Sistema', codigo: '754', icone: 'Building2', tipo: 'banco' },
  { nome: 'Banco Sofisa', codigo: '637', icone: 'Building2', tipo: 'banco' },
  { nome: 'Banco Sumitomo Mitsui', codigo: '464', icone: 'Building2', tipo: 'banco' },
  { nome: 'Banco Topázio', codigo: '082', icone: 'Building2', tipo: 'banco' },
  { nome: 'Banco Toyota', codigo: '387', icone: 'Building2', tipo: 'banco' },
  { nome: 'Banco Triângulo', codigo: '634', icone: 'Building2', tipo: 'banco' },
  { nome: 'Banco Tricury', codigo: '634', icone: 'Building2', tipo: 'banco' },
  { nome: 'Banco UBS', codigo: '015', icone: 'Building2', tipo: 'banco' },
  { nome: 'Banco Unicred', codigo: '136', icone: 'Building2', tipo: 'cooperativa' },
  { nome: 'Banco Uniprime', codigo: '084', icone: 'Building2', tipo: 'cooperativa' },
  { nome: 'Banco Votorantim', codigo: '655', icone: 'Building2', tipo: 'banco' },
  { nome: 'Banco VR', codigo: '610', icone: 'Building2', tipo: 'banco' },
  { nome: 'Banco Woori', codigo: '124', icone: 'Building2', tipo: 'banco' },
  { nome: 'Banco Yamaha', codigo: '475', icone: 'Building2', tipo: 'banco' },
  { nome: 'Banco Zogbi', codigo: '654', icone: 'Building2', tipo: 'banco' },
  
  // Cooperativas de Crédito
  { nome: 'Sicredi', codigo: '748', icone: 'Building2', tipo: 'cooperativa' },
  { nome: 'Sicoob', codigo: '756', icone: 'Building2', tipo: 'cooperativa' },
  { nome: 'Unicred', codigo: '136', icone: 'Building2', tipo: 'cooperativa' },
  { nome: 'Cresol', codigo: '133', icone: 'Building2', tipo: 'cooperativa' },
  { nome: 'Ailos', codigo: '085', icone: 'Building2', tipo: 'cooperativa' },
  
  // Fintechs
  { nome: 'PicPay', codigo: '380', icone: 'CreditCard', tipo: 'fintech' },
  { nome: 'Mercado Pago', codigo: '323', icone: 'CreditCard', tipo: 'fintech' },
  { nome: 'PagSeguro', codigo: '290', icone: 'CreditCard', tipo: 'fintech' },
  { nome: 'Stone', codigo: '197', icone: 'CreditCard', tipo: 'fintech' },
  { nome: 'Cielo', codigo: '362', icone: 'CreditCard', tipo: 'fintech' },
  { nome: 'Rede', codigo: '174', icone: 'CreditCard', tipo: 'fintech' },
  { nome: 'GetNet', codigo: '177', icone: 'CreditCard', tipo: 'fintech' },
  { nome: 'Banco Original', codigo: '212', icone: 'Building2', tipo: 'fintech' },
  
  // Corretoras
  { nome: 'XP Investimentos', codigo: '102', icone: 'TrendingUp', tipo: 'corretora' },
  { nome: 'Rico', codigo: '332', icone: 'TrendingUp', tipo: 'corretora' },
  { nome: 'Clear', codigo: '085', icone: 'TrendingUp', tipo: 'corretora' },
  { nome: 'Avenue', codigo: '085', icone: 'TrendingUp', tipo: 'corretora' },
  { nome: 'BTG Pactual', codigo: '208', icone: 'TrendingUp', tipo: 'corretora' },
  { nome: 'Genial Investimentos', codigo: '278', icone: 'TrendingUp', tipo: 'corretora' },
  { nome: 'Modal', codigo: '746', icone: 'TrendingUp', tipo: 'corretora' },
  { nome: 'Toro Investimentos', codigo: '352', icone: 'TrendingUp', tipo: 'corretora' },
  { nome: 'Guide Investimentos', codigo: '177', icone: 'TrendingUp', tipo: 'corretora' },
  { nome: 'Easynvest', codigo: '140', icone: 'TrendingUp', tipo: 'corretora' },
  { nome: 'Inter Invest', codigo: '077', icone: 'TrendingUp', tipo: 'corretora' },
  { nome: 'Nubank Invest', codigo: '260', icone: 'TrendingUp', tipo: 'corretora' },
];


