export const AREAS_DIREITO = {
  CIVIL: "Direito Civil",
  FAMILIA: "Direito de Família",
  IMOBILIARIO: "Direito Imobiliário",
  TRABALHO: "Direito do Trabalho",
  EMPRESARIAL: "Direito Empresarial / Comercial",
  PENAL: "Direito Penal",
  ADMINISTRATIVO: "Direito Administrativo / Público",
  TRIBUTARIO: "Direito Tributário",
  PREVIDENCIARIO: "Direito Previdenciário",
} as const;

export const TIPOS_ACAO: Record<string, string[]> = {
  [AREAS_DIREITO.CIVIL]: [
    "Ação de Cobrança",
    "Ação de Indenização por Danos Morais",
    "Ação de Indenização por Danos Materiais",
    "Ação de Execução de Título Extrajudicial",
    "Ação de Consignação em Pagamento",
    "Ação Declaratória",
    "Ação Anulatória",
    "Ação de Usucapião",
    "Ação de Reintegração de Posse",
    "Ação de Manutenção de Posse",
    "Ação de Busca e Apreensão",
    "Ação Revisional de Contrato",
    "Ação de Rescisão Contratual",
    "Ação de Cumprimento de Contrato",
  ],
  [AREAS_DIREITO.FAMILIA]: [
    "Ação de Divórcio",
    "Ação de Separação Judicial",
    "Ação de Guarda e Responsabilidade",
    "Ação de Regulamentação de Visitas",
    "Ação de Alimentos",
    "Ação de Exoneração de Alimentos",
    "Ação de Investigação de Paternidade",
    "Adoção",
    "Interdição / Curatela",
  ],
  [AREAS_DIREITO.IMOBILIARIO]: [
    "Ação de Despejo",
    "Ação Renovatória de Locação",
    "Ação Revisional de Aluguel",
    "Ação de Nunciação de Obra Nova",
  ],
  [AREAS_DIREITO.TRABALHO]: [
    "Reclamação Trabalhista",
    "Ação de Reconhecimento de Vínculo Empregatício",
    "Ação de Cobrança de Verbas Rescisórias",
    "Ação de Danos Morais Trabalhistas",
    "Ação de Equiparação Salarial",
  ],
  [AREAS_DIREITO.EMPRESARIAL]: [
    "Ação de Falência",
    "Ação de Recuperação Judicial",
    "Ação de Dissolução de Sociedade",
    "Ação de Execução Fiscal",
    "Ação Monitória",
    "Ação de Prestação de Contas",
  ],
  [AREAS_DIREITO.PENAL]: [
    "Ação Penal Pública",
    "Ação Penal Privada",
    "Queixa-Crime",
    "Habeas Corpus",
    "Revisão Criminal",
  ],
  [AREAS_DIREITO.ADMINISTRATIVO]: [
    "Mandado de Segurança",
    "Ação Popular",
    "Ação Civil Pública",
    "Ação de Improbidade Administrativa",
    "Ação contra o Estado (indenizatória, obrigação de fazer etc.)",
  ],
  [AREAS_DIREITO.TRIBUTARIO]: [
    "Ação Anulatória de Débito Fiscal",
    "Ação Declaratória de Inexistência de Relação Jurídico-Tributária",
    "Ação de Repetição de Indébito",
    "Mandado de Segurança Tributário",
  ],
  [AREAS_DIREITO.PREVIDENCIARIO]: [
    "Ação de Concessão de Benefício (aposentadoria, auxílio, pensão)",
    "Ação Revisional de Benefício",
    "Ação de Restabelecimento de Benefício",
    "Ação contra o INSS",
  ],
};

export const STATUS_PROCESSO = {
  SITUACAO_GERAL: {
    label: "Situação Geral",
    status: [
      { value: "em_andamento", label: "Em andamento", color: "bg-blue-500" },
      { value: "concluido", label: "Encerrado", color: "bg-green-500" },
      { value: "suspenso", label: "Suspenso", color: "bg-yellow-500" },
      { value: "arquivado", label: "Arquivado", color: "bg-gray-500" },
      { value: "extinto", label: "Extinto", color: "bg-red-500" },
    ],
  },
  FASE_PROCESSUAL: {
    label: "Fase Processual",
    status: [
      { value: "distribuido", label: "Distribuído", color: "bg-blue-400" },
      { value: "aguardando_citacao", label: "Aguardando citação", color: "bg-yellow-400" },
      { value: "citado", label: "Citado", color: "bg-green-400" },
      { value: "em_contestacao", label: "Em contestação", color: "bg-orange-400" },
      { value: "em_instrucao", label: "Em instrução", color: "bg-purple-400" },
      { value: "concluso_decisao", label: "Concluso para decisão", color: "bg-indigo-400" },
      { value: "sentenciado", label: "Sentenciado", color: "bg-teal-400" },
      { value: "em_recurso", label: "Em recurso", color: "bg-pink-400" },
      { value: "aguardando_transito", label: "Aguardando trânsito em julgado", color: "bg-cyan-400" },
    ],
  },
  RESULTADO: {
    label: "Resultado",
    status: [
      { value: "ganha", label: "Ganha", color: "bg-green-600" },
      { value: "perdida", label: "Perdida", color: "bg-red-600" },
      { value: "parcial", label: "Parcialmente procedente", color: "bg-yellow-600" },
      { value: "improcedente", label: "Improcedente", color: "bg-orange-600" },
      { value: "indeferida", label: "Indeferida", color: "bg-gray-600" },
      { value: "acordo", label: "Acordo homologado", color: "bg-blue-600" },
      { value: "extinta_sem_merito", label: "Extinta sem julgamento de mérito", color: "bg-purple-600" },
      { value: "extinta_com_merito", label: "Extinta com julgamento de mérito", color: "bg-indigo-600" },
      { value: "anulada", label: "Anulada", color: "bg-red-700" },
    ],
  },
  EXECUCAO: {
    label: "Execução",
    status: [
      { value: "cumprimento_sentenca", label: "Em fase de cumprimento de sentença", color: "bg-green-500" },
      { value: "em_execucao", label: "Em execução", color: "bg-blue-500" },
      { value: "bloqueio_bens", label: "Bloqueio de bens", color: "bg-yellow-500" },
      { value: "pagamento_efetuado", label: "Pagamento efetuado", color: "bg-green-600" },
    ],
  },
  RECURSOS: {
    label: "Recursos",
    status: [
      { value: "em_apelacao", label: "Em apelação", color: "bg-blue-500" },
      { value: "em_agravo", label: "Em agravo", color: "bg-orange-500" },
      { value: "em_recurso_especial", label: "Em recurso especial", color: "bg-purple-500" },
      { value: "em_recurso_extraordinario", label: "Em recurso extraordinário", color: "bg-indigo-500" },
      { value: "retornou_tribunal", label: "Retornou do tribunal", color: "bg-teal-500" },
    ],
  },
  OUTROS: {
    label: "Outros",
    status: [
      { value: "aguardando_audiencia", label: "Aguardando audiência", color: "bg-yellow-400" },
      { value: "aguardando_despacho", label: "Aguardando despacho", color: "bg-orange-400" },
      { value: "aguardando_manifestacao", label: "Aguardando manifestação", color: "bg-blue-400" },
      { value: "aguardando_pericia", label: "Aguardando perícia", color: "bg-purple-400" },
    ],
  },
} as const;

export const DATAS_CRONOLOGIA = [
  { key: "data_distribuicao", label: "Data de distribuição", description: "Quando o processo foi protocolado" },
  { key: "data_citacao", label: "Data de citação/intimação", description: "Quando a parte foi oficialmente notificada" },
  { key: "data_contestacao", label: "Data de contestação", description: "Prazo para defesa" },
  { key: "data_audiencia_conciliacao", label: "Audiência de conciliação", description: "Primeira tentativa de acordo" },
  { key: "data_audiencia_instrucao", label: "Audiência de instrução/julgamento", description: "Oitiva de testemunhas e alegações finais" },
  { key: "data_sentenca", label: "Data da sentença", description: "Decisão de 1ª instância" },
  { key: "data_publicacao_sentenca", label: "Publicação da sentença", description: "Início do prazo para recurso" },
  { key: "data_recurso", label: "Data de recurso", description: "Quando o advogado interpôs recurso" },
  { key: "data_transito_julgado", label: "Trânsito em julgado", description: "Quando a decisão se torna definitiva" },
  { key: "data_arquivamento", label: "Arquivamento", description: "Encerramento do processo" },
  { key: "data_cumprimento_sentenca", label: "Cumprimento de sentença", description: "Início da execução" },
  { key: "data_acordo", label: "Data de acordo", description: "Quando foi firmado ou homologado" },
  { key: "data_pagamento_liquidacao", label: "Pagamento / liquidação", description: "Quando houve cumprimento da obrigação" },
  { key: "data_limite_prazo", label: "Data limite de prazo processual", description: "Último dia útil para peticionar ou recorrer" },
] as const;

